#pragma once

// 
#define NET_HEIGHT_THRESHOLD 8.5f
#define LET_ZONE_THRESHOLD 0.0f

// PHYSICS
#define BALL_MASS 0.146f
#define BALL_THROW_HEIGHT 5.0f

#define SPEED_PLAYER 50.0f
#define BOUNCE_VELOCITY_DECAY 0.75f
#define GROUND_FRICTION 0.0125f
#define SERVE_STRENGTH 75.0f

// PLACEMENT
#define Z_HEIGHT_CORRECTION 15.0f
#define SERVING_DIRECTION_OFFSET_X 70
#define SERVING_DIRECTION_OFFSET_Y 15
#define BALL_SERVING_OFFSET_X 5
#define BALL_SERVING_OFFSET_Y 5

// INPUT
#define CONTROLLER_DEADZONE 0.25f