#pragma once

// 
#define NET_HEIGHT_THRESHOLD 8.5f
#define LET_ZONE_THRESHOLD 10.0f
#define ACCURACY_CORRECTION 0.97f

// Physics
#define BALL_MASS 0.146f
#define BALL_THROW_HEIGHT 5.0f
#define BALL_STOPPED_EPSILON 0.01f

#define PLAYER_SPEED 50.0f
#define BOUNCE_VELOCITY_DECAY 0.75f
#define GROUND_FRICTION 0.0125f
#define SERVE_STRENGTH 75.0f

#define NET_HIT_BOUNCE_DECAY -1.25f
#define LET_HIT_BOUNCE_DECAY_XY -0.45f;
#define LET_HIT_BOUNCE_DECAY_Z -1.10f;

// Visual Placement
#define Z_HEIGHT_CORRECTION 15.0f
#define SERVING_DIRECTION_OFFSET_X 70
#define SERVING_DIRECTION_OFFSET_Y 15
#define BALL_SERVING_OFFSET_X 5
#define BALL_SERVING_OFFSET_Y 5

// Input
#define CONTROLLER_DEADZONE 0.25f